/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        "login": [],
        "logout": [],
        "storage.local": [
            {
                "name": "path",
                "required": true
            }
        ]
    }
}
export {};
